### ISSUE TITLE
Traits with object values are not serialised correctly

### ISSUE THREAD

**Issue by pwfcurry** [expo/expo-analytics-segment#2]
I'm trying to pass a "company" trait - map of values - to `Expo.Segment.identify(..., traits)`.

In our android app, the "company" object is sent as a string of the JSON instead of a Map.

The offending method is here:
https://github.com/expo/expo-analytics-segment/blob/master/android/src/main/java/expo/modules/analytics/segment/SegmentModule.java#L60

Example raw payload:
```json
{
  "traits": {
    "company": "{\"id\":\"abc123\", ...
    ...
}
```

"company" is defined as an object here: https://segment.com/docs/spec/identify/

This is handled correctly in iOS:
```json
  "traits": {
    "company": {
      "id": "abc123",
```

Interestingly com.segment.analytics.Traits does not have any mention of company.

**Comment by sjchmiela** [comment]
Thank you for the issue submission! I think I fixed it in https://github.com/expo/expo/pull/2517, you'll be able to test the fix yourself in the upcoming SDK 31. 🙂
